b1
Oleksandr-Radovets/bookApp pull request #1
Opened 2023-09-27 21:48 UTC by Oleksandr-Radovets

2023-09-28 09:46 UTC, Rommelua requested changes

2023-09-28 09:46 UTC, Rommelua commented on src/main/java/com/example/bookwebstoryspringboot/repository/impl/BookRepositoryImpl.java
> +        return null;
add implementation

2023-10-01 09:04 UTC, sokimaaa commented on src/main/java/com/example/bookwebstoryspringboot/entity/Book.java
> +    }
I would suggest using the Lombok library to reduce boilerplate code, e.g. 
you can replace all getters and setters with only two annotations from Lombok - @Getter and @Setter

2023-10-01 09:05 UTC, sokimaaa commented on src/main/java/com/example/bookwebstoryspringboot/repository/impl/BookRepositoryImpl.java
> +    }
```suggestion
    public Book save(Book book) {
        EntityTransaction entityTransaction = null;

        try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
            entityTransaction = entityManager.getTransaction();
            entityManager.persist(book);
            entityTransaction.commit();
        } catch (Exception e) {
            if (entityTransaction != null) {
                entityTransaction.rollback();
            } else {
                throw new RuntimeException("Can't save " + book + " " + e);
            }
        }
        return book;
    }
```

2023-10-01 09:06 UTC, sokimaaa commented on src/main/java/com/example/bookwebstoryspringboot/repository/impl/BookRepositoryImpl.java
> +
remove redundant empty line
```suggestion
        try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
            TypedQuery<Book> query = entityManager.createQuery("SELECT b.id, b.description,"
                    + "b.title,b.author,"
                    + "b.coverImage, b.isbn, b.price FROM Book b", Book.class);
            return query.getResultList();
        } catch (Exception e) {
            throw new RuntimeException("there are no books");
        }
```

2023-10-03 11:48 UTC, Rommelua approved these changes

2023-10-03 11:48 UTC, Rommelua commented on src/main/java/com/example/bookwebstoryspringboot/entity/Book.java
> +    @Id
```suggestion
public class Book {
    @Id
```

2023-10-12 13:06 UTC, merged